FROM docker.io/library/node:24-bookworm AS dev

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN chmod +x ./scripts/dev-entrypoint.sh
EXPOSE 4200
CMD ["./scripts/dev-entrypoint.sh"]

FROM docker.io/library/node:24-bookworm AS build

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM docker.io/library/nginx:1.27-alpine AS prod

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist/finplan-frontend/browser /usr/share/nginx/html
EXPOSE 80
